name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)
# Pipeline triggers on any branch and tag
trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      ref: refs/tags/1.1.11
      endpoint: statisticsnorway (6)

# Pipeline will be run on this base image
pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Hemmeligheter
  - name: fullSha
    value: '$(Build.SourceVersion)'

jobs:
  - job: dockerBuildAndDockerPush
    displayName: 'Build Docker image for dapla cli'
    steps:
      - template: docker/docker-build-image-and-push-to-gcr.yml@templates
        parameters:
          imageName: 'eu.gcr.io/prod-bip/ssb/dapla/dapla-cli'
          repoName: 'prod-bip/ssb/dapla/dapla-cli'